spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sponti}
    username: ${SPRING_DATASOURCE_USERNAME:sponti}
    password: ${SPRING_DATASOURCE_PASSWORD:sponti}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,modulith,firebase,prometheus

app:
  cors:
    allowed-origin: ${APP_CORS_ALLOWED_ORIGIN:http://localhost:8100}
  security:
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:0123456789012345678901234567890123456789012345678901234567890123}
