package com.mgrtech.sponti_api.shared.error;

public enum ApiErrorCode {
    INVALID_REQUEST("INVALID_REQUEST"),
    MALFORMED_JSON("MALFORMED_JSON"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    AUTHENTICATION_REQUIRED("AUTHENTICATION_REQUIRED"),
    UNSUPPORTED_AUTHENTICATION("UNSUPPORTED_AUTHENTICATION"),
    BAD_CREDENTIALS("BAD_CREDENTIALS"),
    INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN"),
    EMAIL_ALREADY_USED("EMAIL_ALREADY_USED"),
    PHONE_NUMBER_ALREADY_USED("PHONE_NUMBER_ALREADY_USED"),
    USER_NOT_FOUND("USER_NOT_FOUND"),
    USER_PREFERENCES_NOT_FOUND_EXCEPTION("USER_NOT_FOUND"),
    AVAILABILITY_RULE_NOT_FOUND("AVAILABILITY_RULE_NOT_FOUND"),
    INVALID_AVAILABILITY_RULE_TIME_RANGE("INVALID_AVAILABILITY_RULE_TIME_RANGE"),
    INVALID_AVAILABILITY_OVERRIDE_TIME_RANGE("INVALID_AVAILABILITY_OVERRIDE_TIME_RANGE"),
    CONTACT_SELF_OPERATION_NOT_ALLOWED("CONTACT_SELF_OPERATION_NOT_ALLOWED"),
    CONTACT_INVITATION_ALREADY_EXISTS("CONTACT_INVITATION_ALREADY_EXISTS"),
    CONTACT_ALREADY_EXISTS("CONTACT_ALREADY_EXISTS"),
    CONTACT_INVITATION_NOT_FOUND("CONTACT_INVITATION_NOT_FOUND"),
    CONTACT_NOT_FOUND("CONTACT_NOT_FOUND"),
    CONTACT_BLOCKED("CONTACT_BLOCKED"),
    MATCHING_DISABLED("MATCHING_DISABLED"),
    PHONE_NUMBER_REQUIRED_FOR_MATCH_ACCEPTANCE("PHONE_NUMBER_REQUIRED_FOR_MATCH_ACCEPTANCE"),
    USER_DOES_NOT_BELONG_TO_MATCH("USER_DOES_NOT_BELONG_TO_MATCH"),
    CHANNEL_NOT_ALLOWED("CHANNEL_NOT_ALLOWED"),
    AVAILABILITY_OVERLAP_NOT_FOUND("AVAILABILITY_OVERLAP_NOT_FOUND"),
    MATCH_SCORE_BELOW_THRESHOLD("MATCH_SCORE_BELOW_THRESHOLD"),
    MATCH_ALREADY_EXISTS("MATCH_ALREADY_EXISTS"),
    MATCH_PROPOSAL_EXPIRED("MATCH_PROPOSAL_EXPIRED"),
    ACCEPTED_CONTACT_NOT_FOUND("ACCEPTED_CONTACT_NOT_FOUND"),
    MATCH_NOT_FOUND("MATCH_NOT_FOUND"),
    MATCH_STATE_CONFLICT("MATCH_STATE_CONFLICT");

    private final String value;

    ApiErrorCode(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }
}
